name: C++ CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libglew-dev \
          libglu1-mesa-dev \
          libgl1-mesa-dev \
          libfreeimage-dev \
          libassimp-dev \
          freeglut3-dev
    
    - name: Build (Debug)
      run: |
        make Debug
    
    - name: Build (Release)
      run: |
        make Release